version: '3'

tasks:
  build-caddy-with-xml-config-adapter:
    desc: Build Caddy with the XML config adapter plugin
    cmds:
      - xcaddy build --with github.com/roshbhatia/caddy-config-adapter-xml=./ --output ./bin/caddy

  docker-up-caddy:
    desc: Start the standard Caddy image
    cmds:
      - docker-compose up standard-caddy

  docker-up-caddy-with-xml-config-adapter:
    desc: Build and start the Caddy image with XML config adapter plugin
    cmds:
      - docker-compose up caddy-with-xml-config-adapter --build 

  docker-down-caddy:
    desc: Stop the standard Caddy image
    cmds:
      - docker-compose stop standard-caddy

  docker-down-caddy-with-xml-config-adapter:
    desc: Stop the Caddy image with XML config adapter plugin
    cmds:
      - docker-compose stop caddy-with-xml-config-adapter
